
package gr.codehub.client;

import gr.codehub.ws.EdWebServices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CodeHubService", targetNamespace = "http://ws.codehub.gr/", wsdlLocation = "http://localhost:9999/ws/hello?wsdl")
public class CodeHubService
    extends Service
{

    private final static URL CODEHUBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CODEHUBSERVICE_EXCEPTION;
    private final static QName CODEHUBSERVICE_QNAME = new QName("http://ws.codehub.gr/", "CodeHubService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CODEHUBSERVICE_WSDL_LOCATION = url;
        CODEHUBSERVICE_EXCEPTION = e;
    }

    public CodeHubService() {
        super(__getWsdlLocation(), CODEHUBSERVICE_QNAME);
    }

    public CodeHubService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CODEHUBSERVICE_QNAME, features);
    }

    public CodeHubService(URL wsdlLocation) {
        super(wsdlLocation, CODEHUBSERVICE_QNAME);
    }

    public CodeHubService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CODEHUBSERVICE_QNAME, features);
    }

    public CodeHubService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CodeHubService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EdWebServices
     */
    @WebEndpoint(name = "CodeHubServicePort")
    public gr.codehub.ws.EdWebServices getCodeHubServicePort() {
        return super.getPort(new QName("http://ws.codehub.gr/", "CodeHubServicePort"), gr.codehub.ws.EdWebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EdWebServices
     */
    @WebEndpoint(name = "CodeHubServicePort")
    public gr.codehub.ws.EdWebServices getCodeHubServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.codehub.gr/", "CodeHubServicePort"), EdWebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CODEHUBSERVICE_EXCEPTION!= null) {
            throw CODEHUBSERVICE_EXCEPTION;
        }
        return CODEHUBSERVICE_WSDL_LOCATION;
    }

}
